// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFDgO_EiWz4DKoifLj-S01NERfY_w0e-4',
    appId: '1:1070419866604:web:96bb11a5dcdea036f606c9',
    messagingSenderId: '1070419866604',
    projectId: 'biletcep',
    authDomain: 'biletcep.firebaseapp.com',
    storageBucket: 'biletcep.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACAM3WWJJqwlutVKG2NIXa3xZImFf63oA',
    appId: '1:1070419866604:android:87e5fc40821089f8f606c9',
    messagingSenderId: '1070419866604',
    projectId: 'biletcep',
    storageBucket: 'biletcep.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDim0C7zTvSqSrAL79Klh4PTF2j_J7Y6IU',
    appId: '1:1070419866604:ios:0e20bea0e2a9e8a0f606c9',
    messagingSenderId: '1070419866604',
    projectId: 'biletcep',
    storageBucket: 'biletcep.appspot.com',
    iosBundleId: 'com.example.riveAnimation',
  );
}
